### ISSUE TITLE
broken links at https://github.com/vitelabs/doc.vite.org/blob/master/docs/introduction/asynchronous-architecture.md

### ISSUE THREAD

**Issue by cp287** [vitelabs/doc.vite.org#1]
At [https://github.com/vitelabs/doc.vite.org/blob/master/docs/introduction/asynchronous-architecture.md](url) link links to hieroglyphs do not work

> 异步请求图解
> 异步通信模型图解

**Comment by cp287** [comment]
my eth address is 0xDE4D5886da98C3A1140260aaF536a2f1262E2948

**Comment by soliury** [comment]
The link is ok, This link is used for vuepress. So you see in markdown is broken, but in doc.vite.org is ok.
